name: PIB_India_Apr_2021

on:
  push:
    tags:
      - 'v2021_Apr'

  workflow_dispatch:

jobs:

  pib_articles:
    runs-on: ubuntu-latest

    env:
      PIB_MONTH: Apr
      PIB_YEAR: 2021

    steps:
      - uses: actions/checkout@v2

      - name: setting_up
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run:  |
          sudo apt update
          sudo apt install --fix-missing -y python3 wkhtmltopdf fd-find poppler-utils
          sudo ln -s $(which fdfind) /usr/bin/fd
          sudo pip install -r requirements.txt

      - name: run script
        run:  |
          source .env
          pib_month ${{ env.PIB_MONTH }} ${{ env.PIB_YEAR }}

      - name: make txt files
        run:  |
          source .env
          pdftxt

      - name: zipup_articles
        run:  |
          cd /home/runner/pib/${{ env.PIB_YEAR }}
          zip -r "/home/runner/PIB_${{ env.PIB_MONTH }}_${{ env.PIB_YEAR }}.zip" ${{ env.PIB_MONTH }}

      - name: zipup_text
        run:  |
          cd /home/runner/pib_text/${{ env.PIB_YEAR }}
          zip -r "/home/runner/PIB_TEXT_${{ env.PIB_MONTH }}_${{ env.PIB_YEAR }}.zip" ${{ env.PIB_MONTH }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PIB }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload articles zip
        id: upload-release-asset-articles
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PIB }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/runner/PIB_${{ env.PIB_MONTH }}_${{ env.PIB_YEAR }}.zip
          asset_name: PIB_${{ env.PIB_MONTH }}_${{ env.PIB_YEAR }}.zip
          asset_content_type: application/zip

      - name: Upload articles text zip
        id: upload-release-asset-articles-text
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PIB }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/runner/PIB_TEXT_${{ env.PIB_MONTH }}_${{ env.PIB_YEAR }}.zip
          asset_name: PIB_TEXT_${{ env.PIB_MONTH }}_${{ env.PIB_YEAR }}.zip
          asset_content_type: application/zip 
